[package]
name = "dna_semantic_compression"
version = "0.2.0"
edition = "2021"
authors = ["Erick Aguilar"]
description = "High-performance genomic quantization engine for semantic data."

[lib]
name = "dna_semantic_compression"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.0", features = ["extension-module"] }
rayon = "1.10.0"
rand = "0.8.5"
half = { version = "2.4.1", features = ["num-traits"] }

